### PR TITLE
cmake: Disable libbpf build by default

### PR DESCRIPTION
**Pull request by nshy**
I have tarantool build failure on current Archlinux version. The issue is libbpf is installed by default on Arch (libbpf is required by iproute2 and it is in turn required by base). Currently the libbpf presense turns eBPF program build which requires clang compiler to be specified explicitly.

I guess CI does not affected simply because libbpf is not installed by default in the configured distros. So let's cherry-pick a patch from upstream which disables eBPF program build by default.

See https://github.com/tarantool/tarantool/issues/7292

### CODE REVIEW

**Review by alyapunov — APPROVED** [review]

**Comment by Totktonada** [comment]
Several nits:

1. Do you consider update of the nghttp2 submodule in tarantool to the latest nghttp2 release ([v1.47.0](https://github.com/nghttp2/nghttp2/releases/tag/v1.47.0))? It already contains the fix. Technically it would be creating of the `nghttp2-1.47.0-tarantool` branch in our fork, push the release commit to it and push our own commits (there is one) upward. I don't insist here.
2. If we'll decide to backport the commit on top of v.1.46.0: since it is a backport of the [upstream commit](https://github.com/nghttp2/nghttp2/commit/dec233b9ef19d0cd81ea9edaa545a2723566a3f8), I would make it explicit from the commit message (using `git cherry-pick -x` or manually). I would also add our own motivation to backport the commit (the explanation you placed in the pull request description looks okay).

**Review by Totktonada — APPROVED** [review]
I'm generally okay. Please, sync with Alexander L. regarding my points. If you'll decide to proceed with backporting, I'll push the patch.

**Comment by Totktonada** [comment]
We agreed to move to v1.47.0. I created the `nghttp2-1.47.0-tarantool` branch, backported submodules removal and set it as a default branch.

So this pull request should be closed?

**Comment by nshy** [comment]
Yeah, let's close.

**Pull request closed without merging**
